### ISSUE TITLE
Basemap Style

### ISSUE THREAD

**Issue by asonnenschein** [azgs/az-agriculture#1]
We can either use an existing basemap (Google, Bing, MapQuest) or we can make our own.  If we have the budget (which it sounds like we do), I think we should make our own basemap using Open Street Map data and Tilemill.  Our end result will be a thematic map and a themed basemap will be a powerful addition.  Using OSM data will allow us to focus primarily on design, because the data has already passed through a standards organization.

Ideas on how we can use design techniques to illustrate a feeling of 'agriculture' would be very helpful.

**Comment by ridavis** [comment]
we've got a good basemap.
