### ISSUE TITLE
add default text to Detail tab

### ISSUE THREAD

**Issue by ridavis** [azgs/az-agriculture#34]
Currently, the "details" tab is blank when there is no location selected. Please add default text that displays when no location is selected:  Please select a location

**Comment by jessica-azgs** [comment]
Done

**Comment by ridavis** [comment]
Yeah, I saw that it was done, you guys are good! There are a couple minor tweaks to incorporate if possible. Sorry about the confusion.

**Comment by jessica-azgs** [comment]
Yeah, I fixed that Friday. That was a bit of a challenge but I got it. The text is updated now.
