### ISSUE TITLE
Anaheim Chilis should be Romaine Lettuce

### ISSUE THREAD

**Issue by ridavis** [azgs/az-agriculture#35]
Please change Anaheim chilis on the "find farms by crop" list to Romaine Lettuce

**Comment by jessica-azgs** [comment]
@ridavis There is already Romaine Lettuce in the list

**Comment by ridavis** [comment]
There should be. But it doesn't display in the list as I currently see it on the map. Instead, I see both Anaheim Chilis and Chili Peppers.

**Comment by jessica-azgs** [comment]
@ridavis This has been updated on the live server. Can you please double check it and then close this issue if it's good?

**Comment by ridavis** [comment]
Looks great, thanks. Yay! i get to close an issue!
